### ISSUE TITLE
7dof robot moves if I use observed joint position as action

### ISSUE THREAD

**Issue by thomasbonenfant** [AirHockeyChallenge/air_hockey_challenge#28]
Hello,
my issue is that if I try to use the observed joint_positions as input and null joint_velocities the 7dof robot will move on the x-z plane and not remain still. Is there an explanation for this?

I think this also causes problems when I try to convert the actions to cartesian acceleration of the end effector.
I do this calculating the next end effector position given the current end effector's position, velocity and the desired acceleration (the action) and then I use the inverse_kinematics function to calculate the next joint position. The joint velocities are calculated with finite differences. When using accelerations in this way I notice the robot tends to go the left If the acceleration towards the right is not enough.

Below is my code to reproduce the problem stated at the beginning

``` python
import numpy as np
from air_hockey_challenge.framework import AirHockeyChallengeWrapper

env = AirHockeyChallengeWrapper(env='7dof-hit', interpolation_order=3)

env_info = env.env_info
joint_pos_ids = env_info['joint_pos_ids']
n_joints = env_info['robot']['n_joints']

obs = env.reset()

done = False

while not done:
    joint_pos = obs[joint_pos_ids]
    joint_vel = np.zeros((n_joints,))

    action = np.vstack((joint_pos, joint_vel))

    obs, reward, done, info = env.step(action)
    env.render()
```

**Comment by PuzeLiu** [comment]
Hi,
I think this problem could potentially happen in the real robot. If you always update your controller set point to the current one, the robot will not maintain static due to the controlling error. Typically, you should have a set point in the agent to avoid this small drifting. As a simple fix, if you move the `joint_pos = obs[joint_pos_ids]` outside the loop, the robot should hold its position. 

For your second issue, the issue could potentially happen in multi-level. You could check if the inverse kinematics solves successfully and potentially also check if the Cartesian trajectory is planned in the robot's reference frame. If you can provide me with an example joint trajectory, I could be more helpful.

**Comment by thomasbonenfant** [comment]
Hi, thank you for your reply.
About the first problem, shouldn't we expect random movements if the controlling error was the cause? And not a bias towards left.

**Comment by PuzeLiu** [comment]
The error will not be random, depending on the model error. For example, if your gravity compensation term is smaller than the actual one. The robot will fall down. But the bias towards the left is pretty strange. I don't think this should happen.  If you could send a trajectory record such as [joint_pos, joint_vel] for each time step, I will help you to check the issue.

**Comment by PuzeLiu** [comment]
The issue has been closed as there are no further updates available.
